<template><div class="fade-in"><h2 class="mb-4"><i class="bi bi-clipboard-check me-2"></i>Solicitudes de Adopción</h2><Loading v-if="cargando"/><div v-else class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Solicitante</th><th>Animal</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="a in adopciones" :key="a.idAdopcion"><td>{{ nombreCompleto(a.usuario) }}</td><td>{{ a.animal.nombre }}</td><td>{{ formatearFecha(a.fechaSolicitud) }}</td><td><span class="badge" :class="`bg-${colorPorEstado(a.estado)}`">{{ formatearEstado(a.estado) }}</span></td><td><button v-if="a.estado==='Pendiente'" class="btn btn-sm btn-success" @click="aprobar(a)"><i class="bi bi-check"></i></button></td></tr></tbody></table></div></div></div></div></template>
<script>
import {ref,onMounted} from 'vue';
import {useAuthStore} from '../../stores/auth';
import Loading from '../../components/common/Loading.vue';
import adopcionService from '../../services/adopcionService';
import animalService from '../../services/animalService';
import organizacionService from '../../services/organizacionService';
import {toast,manejarErrorAPI} from '../../utils/alertas';
import {colorPorEstado,formatearEstado,formatearFecha,nombreCompleto} from '../../utils/helpers';
export default{name:'OrganizacionAdopciones',components:{Loading},setup(){const authStore=useAuthStore();const cargando=ref(true);const adopciones=ref([]);const cargar=async()=>{try{const org=await organizacionService.getByUsuario(authStore.usuarioActual.idUsuario);const animales=await animalService.getByOrganizacion(org.data.idOrganizacion);const todasAdopciones=await Promise.all(animales.data.map(a=>adopcionService.getByAnimal(a.idAnimal)));adopciones.value=todasAdopciones.flatMap(r=>r.data);}catch(e){manejarErrorAPI(e);}finally{cargando.value=false;}};const aprobar=async(a)=>{try{await adopcionService.update(a.idAdopcion,{...a,estado:'Aprobada'});toast('Adopción aprobada','success');await cargar();}catch(e){manejarErrorAPI(e);}};onMounted(()=>cargar());return{cargando,adopciones,aprobar,colorPorEstado,formatearEstado,formatearFecha,nombreCompleto};}}</script>
